packages:
  - .

allowBuilds:
  '@google/genai': false
  '@sentry/cli': true
  '@tailwindcss/oxide': true
  core-js: false
  core-js-pure: true
  esbuild: true
  protobufjs: false
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@sentry/cli"
  - "@tailwindcss/oxide"
  - "unrs-resolver"
