// Automatically generated by scripts/build-tokens.mjs. Do not edit manually.

export const tokens = {
  "primitives": {
    "color": {
      "gallery": "#f5f3ed",
      "paper": "#fcfbf7",
      "architecture": "#ecebe5",
      "mist": "#dce9ec",
      "ink": "#172126",
      "body-copy": "#3f4a4f",
      "quiet": "#556168",
      "sky": "#4f7787",
      "sky-wash": "#dce9ec",
      "sand": "#b58c54",
      "pine": "#3f6b5a",
      "clay": "#9a654d",
      "rule": "#d6d8d2",
      "error": "#924333",
      "focus": "#315f73"
    },
    "font": {
      "family": {
        "sans": "var(--font-instrument-sans), sans-serif",
        "serif": "var(--font-source-serif), serif"
      },
      "size": {
        "xs": "0.72rem",
        "sm": "0.84rem",
        "base": "1rem",
        "lg": "1.12rem",
        "xl": "1.25rem",
        "2xl": "1.75rem",
        "3xl": "2.45rem",
        "hero": "clamp(3.4rem, 7.8vw, 6rem)"
      }
    },
    "space": {
      "gutter": "clamp(1rem, 2vw, 2rem)",
      "section": "clamp(4.5rem, 6vw, 6.75rem)",
      "content-max": "77.5rem"
    },
    "duration": {
      "instant": "0ms",
      "fast": "150ms",
      "interface": "200ms",
      "reveal": "600ms"
    },
    "easing": {
      "standard": "cubic-bezier(0.16, 1, 0.3, 1)",
      "interface": "ease-out"
    },
    "radius": {
      "media": "16px",
      "content": "0.5rem",
      "control": "0.375rem"
    },
    "legacy": {
      "dimension": {
        "negative-1-25rem": "-1.25rem",
        "negative-1-5rem": "-1.5rem",
        "negative-1px": "-1px",
        "negative-2px": "-2px",
        "negative-2rem": "-2rem",
        "negative-5rem": "-5rem",
        "positive-0-12rem": "0.12rem",
        "positive-0-14em": "0.14em",
        "positive-0-15rem": "0.15rem",
        "positive-0-16rem": "0.16rem",
        "positive-0-25rem": "0.25rem",
        "positive-0-28rem": "0.28rem",
        "positive-0-2rem": "0.2rem",
        "positive-0-35rem": "0.35rem",
        "positive-0-375rem": "0.375rem",
        "positive-0-38rem": "0.38rem",
        "positive-0-3rem": "0.3rem",
        "positive-0-45rem": "0.45rem",
        "positive-0-4rem": "0.4rem",
        "positive-0-55rem": "0.55rem",
        "positive-0-5rem": "0.5rem",
        "positive-0-65rem": "0.65rem",
        "positive-0-6rem": "0.6rem",
        "positive-0-72rem": "0.72rem",
        "positive-0-75rem": "0.75rem",
        "positive-0-7rem": "0.7rem",
        "positive-0-82rem": "0.82rem",
        "positive-0-85rem": "0.85rem",
        "positive-0-8rem": "0.8rem",
        "positive-0-9rem": "0.9rem",
        "positive-1-15rem": "1.15rem",
        "positive-1-1rem": "1.1rem",
        "positive-1-25rem": "1.25rem",
        "positive-1-2rem": "1.2rem",
        "positive-1-35rem": "1.35rem",
        "positive-1-45rem": "1.45rem",
        "positive-1-4rem": "1.4rem",
        "positive-1-5rem": "1.5rem",
        "positive-1-6rem": "1.6rem",
        "positive-1-75rem": "1.75rem",
        "positive-1-8rem": "1.8rem",
        "positive-1240px": "1240px",
        "positive-12rem": "12rem",
        "positive-14px": "14px",
        "positive-1rem": "1rem",
        "positive-2-25rem": "2.25rem",
        "positive-2-4rem": "2.4rem",
        "positive-2-5rem": "2.5rem",
        "positive-2-75rem": "2.75rem",
        "positive-2-8rem": "2.8rem",
        "positive-2px": "2px",
        "positive-2rem": "2rem",
        "positive-3-25rem": "3.25rem",
        "positive-3-5rem": "3.5rem",
        "positive-3-75rem": "3.75rem",
        "positive-3px": "3px",
        "positive-3rem": "3rem",
        "positive-4-5rem": "4.5rem",
        "positive-4-6rem": "4.6rem",
        "positive-4-75rem": "4.75rem",
        "positive-42-5rem": "42.5rem",
        "positive-4px": "4px",
        "positive-4rem": "4rem",
        "positive-5-25rem": "5.25rem",
        "positive-5rem": "5rem",
        "positive-5-75rem": "5.75rem",
        "positive-6-25rem": "6.25rem",
        "positive-6-5rem": "6.5rem",
        "positive-6-75rem": "6.75rem",
        "positive-6rem": "6rem",
        "positive-7-25rem": "7.25rem",
        "positive-7-4rem": "7.4rem",
        "positive-7-5rem": "7.5rem",
        "positive-7rem": "7rem",
        "positive-8-25rem": "8.25rem",
        "positive-8-75rem": "8.75rem",
        "positive-9999px": "9999px",
        "positive-9rem": "9rem"
      },
      "color": {
        "value-111827": "#111827",
        "value-202321": "#202321",
        "value-356d8d": "#356d8d",
        "value-406b58": "#406b58",
        "value-68716d": "#68716d",
        "value-a34132": "#a34132",
        "value-a47b46": "#a47b46",
        "value-c4c8c2": "#c4c8c2",
        "value-d8dad5": "#d8dad5",
        "value-e5eee8": "#e5eee8",
        "value-e5eef3": "#e5eef3",
        "value-f1e8dc": "#f1e8dc",
        "value-f8f3ed": "#f8f3ed",
        "value-fbfbf8": "#fbfbf8",
        "value-rgba-255-255-255-0-08": "rgba(255, 255, 255, 0.08)",
        "value-rgba-255-255-255-0-12": "rgba(255, 255, 255, 0.12)",
        "value-rgba-255-255-255-0-22": "rgba(255, 255, 255, 0.22)",
        "value-18252b": "#18252b",
        "value-22c55e": "#22c55e",
        "value-315744": "#315744",
        "value-33464d": "#33464d",
        "value-344a55": "#344a55",
        "value-363a37": "#363a37",
        "value-378264": "#378264",
        "value-394a4f": "#394a4f",
        "value-496472": "#496472",
        "value-77562d": "#77562d",
        "value-7b807e": "#7b807e",
        "value-7c3029": "#7c3029",
        "value-ad7c43": "#ad7c43",
        "value-afb4af": "#afb4af",
        "value-b91c1c": "#b91c1c",
        "value-c6d8cd": "#c6d8cd",
        "value-c7cdcc": "#c7cdcc",
        "value-d4d8d3": "#d4d8d3",
        "value-dde1de": "#dde1de",
        "value-decdb8": "#decdb8",
        "value-e7e8e4": "#e7e8e4",
        "value-e8e8e1": "#e8e8e1",
        "value-ecece6": "#ecece6",
        "value-eceeea": "#eceeea",
        "value-eef1ef": "#eef1ef",
        "value-efefea": "#efefea",
        "value-f0f0eb": "#f0f0eb",
        "value-f1f1ec": "#f1f1ec",
        "value-f4e6e2": "#f4e6e2",
        "value-f4f3ee": "#f4f3ee",
        "value-f4f4ef": "#f4f4ef",
        "value-f4f6f4": "#f4f6f4",
        "value-f6f6f2": "#f6f6f2",
        "value-f7f6f1": "#f7f6f1",
        "value-f8f8f4": "#f8f8f4",
        "value-fee2e2": "#fee2e2",
        "value-fff1ed": "#fff1ed",
        "value-rgb-23-33-38-10": "rgb(23 33 38 / 10%)",
        "value-rgb-255-255-255-10": "rgb(255 255 255 / 10%)",
        "value-rgb-255-255-255-45": "rgb(255 255 255 / 45%)",
        "value-rgba-0-0-0-0-24": "rgba(0, 0, 0, 0.24)",
        "value-rgba-0-0-0-0-28": "rgba(0, 0, 0, 0.28)",
        "value-rgba-0-0-0-0-5": "rgba(0, 0, 0, 0.5)",
        "value-rgba-0-0-0-04": "rgba(0, 0, 0, .04)",
        "value-rgba-10-15-20-0-25": "rgba(10, 15, 20, 0.25)",
        "value-rgba-10-15-20-0-45": "rgba(10, 15, 20, 0.45)",
        "value-rgba-10-15-20-0-60": "rgba(10, 15, 20, 0.60)",
        "value-rgba-10-15-20-0-85": "rgba(10, 15, 20, 0.85)",
        "value-rgba-12-18-22-0-72": "rgba(12, 18, 22, 0.72)",
        "value-rgba-12-18-22-0-84": "rgba(12, 18, 22, 0.84)",
        "value-rgba-12-28-30-35": "rgba(12,28,30,.35)",
        "value-rgba-17-24-25-0-78": "rgba(17, 24, 25, 0.78)",
        "value-rgba-20-25-22-28": "rgba(20, 25, 22, .28)",
        "value-rgba-20-25-22-36": "rgba(20, 25, 22, .36)",
        "value-rgba-20-26-23-18": "rgba(20, 26, 23, .18)",
        "value-rgba-20-26-23-2": "rgba(20, 26, 23, .2)",
        "value-rgba-23-27-26-0-66": "rgba(23, 27, 26, 0.66)",
        "value-rgba-23-28-27-08": "rgba(23, 28, 27, .08)",
        "value-rgba-23-33-38-0-22": "rgba(23, 33, 38, 0.22)",
        "value-rgba-23-33-38-0-34": "rgba(23, 33, 38, 0.34)",
        "value-rgba-25-31-28-12": "rgba(25, 31, 28, .12)",
        "value-rgba-25-31-28-15": "rgba(25, 31, 28, .15)",
        "value-rgba-251-251-248-0-08": "rgba(251, 251, 248, 0.08)",
        "value-rgba-251-251-248-0-1": "rgba(251, 251, 248, 0.1)",
        "value-rgba-251-251-248-0-32": "rgba(251, 251, 248, 0.32)",
        "value-rgba-251-251-248-0-72": "rgba(251, 251, 248, 0.72)",
        "value-rgba-251-251-248-97": "rgba(251, 251, 248, .97)",
        "value-rgba-251-251-248-98": "rgba(251, 251, 248, .98)",
        "value-rgba-255-255-255-0-16": "rgba(255, 255, 255, 0.16)",
        "value-rgba-255-255-255-0-3": "rgba(255, 255, 255, 0.3)",
        "value-rgba-255-255-255-0-35": "rgba(255, 255, 255, 0.35)",
        "value-rgba-255-255-255-0-42": "rgba(255, 255, 255, 0.42)",
        "value-rgba-255-255-255-0-6": "rgba(255, 255, 255, 0.6)",
        "value-rgba-255-255-255-0-72": "rgba(255, 255, 255, 0.72)",
        "value-rgba-255-255-255-0-9": "rgba(255, 255, 255, 0.9)",
        "value-rgba-255-255-255-0-93": "rgba(255, 255, 255, 0.93)",
        "value-rgba-255-255-255-0-94": "rgba(255, 255, 255, 0.94)",
        "value-rgba-255-255-255-02": "rgba(255,255,255,.02)",
        "value-rgba-255-255-255-25": "rgba(255,255,255,.25)",
        "value-rgba-255-255-255-55": "rgba(255,255,255,.55)",
        "value-rgba-255-255-255-78": "rgba(255,255,255,.78)",
        "value-rgba-27-42-49-0-08": "rgba(27, 42, 49, 0.08)",
        "value-rgba-30-43-45-0-82": "rgba(30, 43, 45, 0.82)",
        "value-rgba-32-35-33-12": "rgba(32, 35, 33, .12)",
        "value-rgba-34-197-94-2": "rgba(34, 197, 94, .2)",
        "value-rgba-40-52-55-0-16": "rgba(40, 52, 55, 0.16)",
        "value-rgba-42-51-50-0-1": "rgba(42, 51, 50, 0.1)",
        "value-rgba-42-51-50-0-14": "rgba(42, 51, 50, 0.14)",
        "value-rgba-42-51-50-0-15": "rgba(42, 51, 50, 0.15)",
        "value-rgba-55-130-100-0-16": "rgba(55, 130, 100, 0.16)"
      }
    }
  },
  "semantics": {
    "surface": {
      "canvas": "#f5f3ed",
      "card": "#fcfbf7",
      "subtle": "#ecebe5",
      "wash": "#dce9ec"
    },
    "text": {
      "primary": "#172126",
      "body": "#3f4a4f",
      "muted": "#556168",
      "inverse": "#ffffff"
    },
    "border": {
      "subtle": "#d6d8d2",
      "focus": "#315f73"
    },
    "accent": {
      "sky": "#4f7787",
      "sand": "#b58c54",
      "pine": "#3f6b5a",
      "clay": "#9a654d"
    },
    "feedback": {
      "error": "#924333"
    },
    "motion": {
      "feedbackDuration": "150ms",
      "transformDuration": "200ms",
      "revealDuration": "600ms",
      "easeOut": "cubic-bezier(0.16, 1, 0.3, 1)"
    }
  },
  "components": {
    "button": {
      "radius": "0.375rem",
      "minHeight": "2.75rem",
      "paddingInline": "0.5rem",
      "fontSize": "0.84rem"
    },
    "badge": {
      "radius": "0.38rem",
      "paddingBlock": "0.2rem",
      "paddingInline": "0.5rem",
      "fontSize": "0.72rem"
    },
    "mediaFrame": {
      "radius": "16px",
      "background": "#ecebe5"
    },
    "voiceSignal": {
      "size": "2.75rem",
      "accent": "#4f7787",
      "active": "#3f6b5a"
    },
    "evidencePlane": {
      "radius": "0.5rem",
      "rule": "#d6d8d2",
      "background": "#fcfbf7"
    },
    "hero": {
      "contentMeasure": "48rem",
      "scrimCenter": "rgb(10 19 25 / 60%)",
      "scrimEdge": "rgb(10 19 25 / 18%)"
    },
    "decisionAperture": {
      "heroSize": "5.5rem",
      "dialogSize": "5rem",
      "stroke": "1.5px"
    },
    "dialog": {
      "radius": "0.5rem",
      "maxWidth": "48rem",
      "ambientShadow": "0 1.6rem 4rem rgb(23 33 38 / 22%)"
    }
  }
} as const;

export type Tokens = typeof tokens;
export type ColorTokens = typeof tokens.primitives.color;
export type SemanticTokens = typeof tokens.semantics;
export type ComponentTokens = typeof tokens.components;
