// Automatically generated by scripts/build-tokens.mjs. Do not edit manually.

export const tokens = {
  "primitives": {
    "color": {
      "gallery": "#fbfbf8",
      "paper": "#ffffff",
      "architecture": "#f0f1f1",
      "mist": "#e7ebec",
      "ink": "#202321",
      "body-copy": "#585d5b",
      "quiet": "#747a77",
      "sky": "#82b8d7",
      "sky-wash": "#ddecf4",
      "sand": "#b99463",
      "rule": "#d8dad8",
      "error": "#a34132",
      "focus": "#356d8d"
    },
    "font": {
      "family": {
        "sans": "var(--font-instrument-sans), sans-serif",
        "serif": "var(--font-source-serif), serif"
      },
      "size": {
        "xs": "0.72rem",
        "sm": "0.84rem",
        "base": "1rem",
        "lg": "1.12rem",
        "xl": "1.25rem",
        "2xl": "1.75rem",
        "3xl": "2.45rem",
        "hero": "3.85rem"
      }
    },
    "space": {
      "gutter": "clamp(1rem, 2vw, 2rem)",
      "section": "clamp(4.5rem, 6vw, 6.75rem)",
      "content-max": "74rem"
    },
    "radius": {
      "media": "16px",
      "content": "0.625rem",
      "control": "0.5rem"
    }
  },
  "semantics": {
    "surface": {
      "canvas": "#fbfbf8",
      "card": "#ffffff",
      "subtle": "#f0f1f1",
      "wash": "#ddecf4"
    },
    "text": {
      "primary": "#202321",
      "body": "#585d5b",
      "muted": "#747a77",
      "inverse": "#ffffff"
    },
    "border": {
      "subtle": "#d8dad8",
      "focus": "#356d8d"
    },
    "accent": {
      "sky": "#82b8d7",
      "sand": "#b99463"
    },
    "feedback": {
      "error": "#a34132"
    }
  },
  "components": {
    "button": {
      "radius": "0.5rem",
      "minHeight": "2.75rem",
      "paddingInline": "0.5rem",
      "fontSize": "0.84rem"
    },
    "badge": {
      "radius": "0.38rem",
      "paddingBlock": "0.2rem",
      "paddingInline": "0.5rem",
      "fontSize": "0.72rem"
    },
    "mediaFrame": {
      "radius": "16px",
      "background": "#f0f1f1"
    },
    "voiceSignal": {
      "size": "10rem",
      "accent": "#82b8d7",
      "active": "#378264"
    }
  }
} as const;

export type Tokens = typeof tokens;
export type ColorTokens = typeof tokens.primitives.color;
export type SemanticTokens = typeof tokens.semantics;
export type ComponentTokens = typeof tokens.components;
