import { execFileSync, spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const packageJson = JSON.parse(readFileSync("package.json", "utf8"));
const workflow = readFileSync(".github/workflows/ci.yml", "utf8");
const stagingWorkflow = readFileSync(".github/workflows/staging-verification.yml", "utf8");
const imageBuilder = readFileSync("scripts/build-public-images.mjs", "utf8");
const workspace = readFileSync("pnpm-workspace.yaml", "utf8");
const canonicalLockfileSha256 = createHash("sha256")
  .update(readFileSync("pnpm-lock.yaml", "utf8").replace(/\r\n/g, "\n"), "utf8")
  .digest("hex");

describe("build environment contract", () => {
  it("pins one Node and pnpm toolchain across package and version-manager files", () => {
    expect(packageJson.packageManager).toBe("pnpm@11.20.0");
    expect(packageJson.engines.node).toBe("24.19.0");
    expect(readFileSync(".node-version", "utf8").trim()).toBe("24.19.0");
    expect(readFileSync(".nvmrc", "utf8").trim()).toBe("24.19.0");
  });

  it("requires frozen lockfiles and strict store-integrity checks", () => {
    expect(workspace).toMatch(/verifyStoreIntegrity:\s*true/);
    expect(workspace).toMatch(/strictStorePkgContentCheck:\s*true/);
    expect(workspace).toMatch(/preferFrozenLockfile:\s*true/);
    expect(workspace).toMatch(/engineStrict:\s*true/);
    expect(workspace).toMatch(/verifyDepsBeforeRun:\s*error/);
    expect(workspace).toMatch(/enableGlobalVirtualStore:\s*false/);
  });

  it("runs an isolated frozen fetch, offline install, and payload check before quality", () => {
    expect(workflow).toMatch(/dependency-integrity:/);
    expect(workflow).toMatch(/pnpm fetch --frozen-lockfile --store-dir/);
    expect(workflow).toMatch(/PNPM_CONFIG_TRUST_LOCKFILE=true/);
    expect(workflow).toMatch(/pnpm install --offline --frozen-lockfile --store-dir/);
    expect(workflow).toMatch(/needs: dependency-integrity/);
    expect(workflow).not.toMatch(/environment:diagnose -- .*store-status/);
    expect(workflow).not.toMatch(/pnpm .*store status/);
    expect(workflow).toMatch(/node-version: 24\.19\.0/);
  });

  it("resolves runner-temporary stores at step runtime instead of job parsing time", () => {
    for (const source of [workflow, stagingWorkflow]) {
      expect(source).not.toMatch(/^ {6}[A-Z_]+:\s*\$\{\{\s*runner\./m);
      expect(source).toMatch(/RAMA_PNPM_STORE_DIR=\$RUNNER_TEMP\/rama-/);
    }
  });

  it("attests the checked-out PR head SHA and keeps generated asset metadata deterministic", () => {
    expect(workflow).toContain("github.event.pull_request.head.sha");
    expect(workflow.match(/ref: \$\{\{ env\.RAMA_RELEASE_COMMIT \}\}/g)).toHaveLength(3);
    expect(workflow).toContain("ci-build-attestation-${{ env.RAMA_RELEASE_COMMIT }}");
    expect(workflow).toMatch(/attestation:\s*\n\s+needs: \[dependency-integrity, quality\]/);
    expect(workflow).toContain("GITHUB_TOKEN: ${{ github.token }}");
    expect(workflow).toMatch(/permissions:\s*\n\s+actions: read\s*\n\s+contents: read/);
    expect(readFileSync("scripts/write-ci-build-attestation.mjs", "utf8")).toContain("authenticated success evidence");
    expect(imageBuilder).not.toContain("rights.updatedAt = new Date().toISOString()");
    expect(packageJson.scripts.prebuild).toContain("verify-public-assets.mjs");
    expect(packageJson.scripts.prebuild).not.toContain("images:build");
    expect(readFileSync(".gitignore", "utf8")).toMatch(/^\/results\.sarif$/m);
  });

  it("refuses to generate an authoritative build attestation locally", () => {
    const result = spawnSync(process.execPath, ["scripts/write-ci-build-attestation.mjs"], {
      cwd: process.cwd(),
      env: { ...process.env, CI: "false", GITHUB_ACTIONS: "false" },
      encoding: "utf8",
    });
    expect(result.status).not.toBe(0);
    expect(`${result.stdout}${result.stderr}`).toContain("only be generated by GitHub Actions");
  });

  it("keeps the lockfile syntax and package manifest readable", () => {
    expect(readFileSync("pnpm-lock.yaml", "utf8")).toMatch(/^lockfileVersion: '9\.0'/);
    expect(canonicalLockfileSha256).toBe("fbe442ca3dbfcca30d14b64960a1628b9d242698e0ef62fda71ff3fc46364d46");
    expect(() => execFileSync(process.execPath, ["-e", "JSON.parse(require('fs').readFileSync('package.json','utf8'))"])).not.toThrow();
  });
});
