import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const tokensDir = path.join(rootDir, 'tokens');
const outputTsPath = path.join(rootDir, 'lib', 'tokens', 'index.ts');
const outputCssPath = path.join(rootDir, 'app', 'design-tokens.css');

export function loadTokenSources(customDir = tokensDir) {
  const loadJson = (filePath) => JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  const primitives = loadJson(path.join(customDir, 'primitives.json'));
  const semantics = loadJson(path.join(customDir, 'semantics.json'));
  const components = loadJson(path.join(customDir, 'components.json'));
  return { primitives, semantics, components };
}

export function flattenTokens(obj, prefix = '', lookup = {}) {
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith('$')) continue;
    const fullPath = prefix ? `${prefix}.${key}` : key;
    if (val && typeof val === 'object' && '$value' in val) {
      lookup[fullPath] = val.$value;
    } else if (val && typeof val === 'object') {
      flattenTokens(val, fullPath, lookup);
    }
  }
  return lookup;
}

export function validateTokenTree(obj, prefix = '') {
  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith('$')) continue;
    const tokenPath = prefix ? `${prefix}.${key}` : key;
    if (!value || typeof value !== 'object') {
      throw new Error(`Invalid token node at ${tokenPath}`);
    }
    if ('$value' in value) {
      for (const field of ['$type', '$description']) {
        if (typeof value[field] !== 'string' || value[field].trim() === '') {
          throw new Error(`Token ${tokenPath} is missing required ${field}`);
        }
      }
      continue;
    }
    validateTokenTree(value, tokenPath);
  }
}

export function resolveValue(val, lookup, visited = new Set()) {
  if (typeof val !== 'string') return val;
  return val.replace(/\{([^}]+)\}/g, (_, key) => {
    if (visited.has(key)) {
      throw new Error(`Circular reference detected in design tokens: ${Array.from(visited).join(' -> ')} -> ${key}`);
    }
    if (lookup[key] === undefined) {
      throw new Error(`Unknown token reference: {${key}}`);
    }
    const nextVisited = new Set(visited);
    nextVisited.add(key);
    return resolveValue(lookup[key], lookup, nextVisited);
  });
}

export function resolveTree(obj, lookup) {
  const result = {};
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith('$')) continue;
    if (val && typeof val === 'object' && '$value' in val) {
      result[key] = resolveValue(val.$value, lookup);
    } else if (val && typeof val === 'object') {
      result[key] = resolveTree(val, lookup);
    } else {
      result[key] = val;
    }
  }
  return result;
}

export function compileTokens(sources) {
  validateTokenTree(sources.primitives);
  validateTokenTree(sources.semantics);
  validateTokenTree(sources.components);
  const lookup = {};
  flattenTokens(sources.primitives, '', lookup);
  flattenTokens(sources.semantics, '', lookup);
  flattenTokens(sources.components, '', lookup);

  const rawPrimitives = resolveTree(sources.primitives, lookup);
  const rawSemantics = resolveTree(sources.semantics, lookup);
  const rawComponents = resolveTree(sources.components, lookup);

  const resolvedPrimitives = rawPrimitives;
  const resolvedSemantics = rawSemantics.semantic || rawSemantics;
  const resolvedComponents = rawComponents.component || rawComponents;

  return {
    primitives: resolvedPrimitives,
    semantics: resolvedSemantics,
    components: resolvedComponents,
  };
}

function cssName(pathParts) {
  return `--rama-${pathParts.join('-')
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9-]+/g, '-')
    .toLowerCase()}`;
}

function flattenResolvedCss(obj, prefix = [], result = []) {
  for (const [key, value] of Object.entries(obj)) {
    const pathParts = [...prefix, key];
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      flattenResolvedCss(value, pathParts, result);
    } else {
      result.push([cssName(pathParts), String(value)]);
    }
  }
  return result;
}

export function renderCss(compiled) {
  const entries = [
    ...flattenResolvedCss(compiled.primitives),
    ...flattenResolvedCss(compiled.semantics),
    ...flattenResolvedCss(compiled.components, ['component']),
  ];
  return `/* Automatically generated by scripts/build-tokens.mjs. Do not edit manually. */\n\n:root {\n${entries
    .map(([name, value]) => `  ${name}: ${value};`)
    .join('\n')}\n}\n`;
}

function assertCurrent(filePath, expected) {
  const actual = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf-8') : '';
  if (actual !== expected) {
    throw new Error(`Generated token artifact is stale: ${path.relative(rootDir, filePath)}. Run pnpm tokens:build.`);
  }
}

export function buildTokens({ check = false } = {}) {
  const sources = loadTokenSources();
  const compiled = compileTokens(sources);

  const tsContent = `// Automatically generated by scripts/build-tokens.mjs. Do not edit manually.

export const tokens = ${JSON.stringify(compiled, null, 2)} as const;

export type Tokens = typeof tokens;
export type ColorTokens = typeof tokens.primitives.color;
export type SemanticTokens = typeof tokens.semantics;
export type ComponentTokens = typeof tokens.components;
`;

  const cssContent = renderCss(compiled);

  if (check) {
    assertCurrent(outputTsPath, tsContent);
    assertCurrent(outputCssPath, cssContent);
    console.log('✓ Rama design-token sources and generated artifacts are valid');
    return compiled;
  }

  fs.mkdirSync(path.dirname(outputTsPath), { recursive: true });
  fs.writeFileSync(outputTsPath, tsContent, 'utf-8');
  fs.writeFileSync(outputCssPath, cssContent, 'utf-8');
  console.log('✓ Rama design tokens compiled to TypeScript and CSS');
  return compiled;
}

// Run if called directly
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  buildTokens({ check: process.argv.includes('--check') });
}
