import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const tokensDir = path.join(rootDir, 'tokens');
const outputTsPath = path.join(rootDir, 'lib', 'tokens', 'index.ts');

export function loadTokenSources(customDir = tokensDir) {
  const loadJson = (filePath) => JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  const primitives = loadJson(path.join(customDir, 'primitives.json'));
  const semantics = loadJson(path.join(customDir, 'semantics.json'));
  const components = loadJson(path.join(customDir, 'components.json'));
  return { primitives, semantics, components };
}

export function flattenTokens(obj, prefix = '', lookup = {}) {
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith('$')) continue;
    const fullPath = prefix ? `${prefix}.${key}` : key;
    if (val && typeof val === 'object' && '$value' in val) {
      lookup[fullPath] = val.$value;
    } else if (val && typeof val === 'object') {
      flattenTokens(val, fullPath, lookup);
    }
  }
  return lookup;
}

export function resolveValue(val, lookup, visited = new Set()) {
  if (typeof val !== 'string') return val;
  return val.replace(/\{([^}]+)\}/g, (_, key) => {
    if (visited.has(key)) {
      throw new Error(`Circular reference detected in design tokens: ${Array.from(visited).join(' -> ')} -> ${key}`);
    }
    if (lookup[key] === undefined) {
      throw new Error(`Unknown token reference: {${key}}`);
    }
    const nextVisited = new Set(visited);
    nextVisited.add(key);
    return resolveValue(lookup[key], lookup, nextVisited);
  });
}

export function resolveTree(obj, lookup) {
  const result = {};
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith('$')) continue;
    if (val && typeof val === 'object' && '$value' in val) {
      result[key] = resolveValue(val.$value, lookup);
    } else if (val && typeof val === 'object') {
      result[key] = resolveTree(val, lookup);
    } else {
      result[key] = val;
    }
  }
  return result;
}

export function compileTokens(sources) {
  const lookup = {};
  flattenTokens(sources.primitives, '', lookup);
  flattenTokens(sources.semantics, '', lookup);
  flattenTokens(sources.components, '', lookup);

  const rawPrimitives = resolveTree(sources.primitives, lookup);
  const rawSemantics = resolveTree(sources.semantics, lookup);
  const rawComponents = resolveTree(sources.components, lookup);

  const resolvedPrimitives = rawPrimitives;
  const resolvedSemantics = rawSemantics.semantic || rawSemantics;
  const resolvedComponents = rawComponents.component || rawComponents;

  return {
    primitives: resolvedPrimitives,
    semantics: resolvedSemantics,
    components: resolvedComponents,
  };
}

export function buildTokens() {
  const sources = loadTokenSources();
  const compiled = compileTokens(sources);

  const tsContent = `// Automatically generated by scripts/build-tokens.mjs. Do not edit manually.

export const tokens = ${JSON.stringify(compiled, null, 2)} as const;

export type Tokens = typeof tokens;
export type ColorTokens = typeof tokens.primitives.color;
export type SemanticTokens = typeof tokens.semantics;
export type ComponentTokens = typeof tokens.components;
`;

  fs.mkdirSync(path.dirname(outputTsPath), { recursive: true });
  fs.writeFileSync(outputTsPath, tsContent, 'utf-8');
  console.log('✓ Rama Realty Design Tokens successfully compiled to lib/tokens/index.ts');
  return compiled;
}

// Run if called directly
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  buildTokens();
}
