import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const tokensDir = path.join(rootDir, 'tokens');
const outputTsPath = path.join(rootDir, 'lib', 'tokens', 'index.ts');

function loadJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
}

const primitives = loadJson(path.join(tokensDir, 'primitives.json'));
const semantics = loadJson(path.join(tokensDir, 'semantics.json'));
const components = loadJson(path.join(tokensDir, 'components.json'));

// Flat resolver for references like {color.gallery}
const lookup = {};

function flatten(obj, prefix = '') {
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith('$')) continue;
    const fullPath = prefix ? `${prefix}.${key}` : key;
    if (val && typeof val === 'object' && '$value' in val) {
      lookup[fullPath] = val.$value;
    } else if (val && typeof val === 'object') {
      flatten(val, fullPath);
    }
  }
}

flatten(primitives);
flatten(semantics);
flatten(components);

function resolveValue(val) {
  if (typeof val !== 'string') return val;
  return val.replace(/\{([^}]+)\}/g, (_, key) => {
    if (lookup[key] !== undefined) {
      return resolveValue(lookup[key]);
    }
    return val;
  });
}

function resolveTree(obj) {
  const result = {};
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith('$')) continue;
    if (val && typeof val === 'object' && '$value' in val) {
      result[key] = resolveValue(val.$value);
    } else if (val && typeof val === 'object') {
      result[key] = resolveTree(val);
    } else {
      result[key] = val;
    }
  }
  return result;
}

const rawPrimitives = resolveTree(primitives);
const rawSemantics = resolveTree(semantics);
const rawComponents = resolveTree(components);

const resolvedPrimitives = rawPrimitives;
const resolvedSemantics = rawSemantics.semantic || rawSemantics;
const resolvedComponents = rawComponents.component || rawComponents;

const tsContent = `// Automatically generated by scripts/build-tokens.mjs. Do not edit manually.

export const tokens = {
  primitives: ${JSON.stringify(resolvedPrimitives, null, 2)},
  semantics: ${JSON.stringify(resolvedSemantics, null, 2)},
  components: ${JSON.stringify(resolvedComponents, null, 2)},
} as const;

export type Tokens = typeof tokens;
export type ColorTokens = typeof tokens.primitives.color;
export type SemanticTokens = typeof tokens.semantics;
export type ComponentTokens = typeof tokens.components;
`;

fs.mkdirSync(path.dirname(outputTsPath), { recursive: true });
fs.writeFileSync(outputTsPath, tsContent, 'utf-8');

console.log('✓ Rama Realty Design Tokens successfully compiled to lib/tokens/index.ts');
